name: becomehope
favicon: null
layout_spectrum: 0.46282
typography_spectrum: 0.1485
title: 'New Hope Church - Greenwood, IN'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2a2119'
    - '#9a8777'
    - '#b21c15'
    - '#bebebd'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
